### ISSUE TITLE
Camera/Screen shake controller

### ISSUE THREAD

**Issue by SyncMQ** [smooth-soup-studios/oh-my-cult#19]
- [x] Manager
  - [x] Call shake from anywhere (static?)
    - [x] Default
    - [x] With options

**Comment by Justwouter** [comment]
### Notes for #25
- Why is the camera required to be a child of the screenshaker?
You can get a reference to the camera via `[serializefield]` or add a camera as a parameter to either the methods or the `ScreenShakeOptions`

- The singleton is not a singleton per se, there should indeed be a single instance of the class but there is nothing preventing the creation of multiple gameobjects with the `ScreenShakeController` in a scene.

- There is currently no way(?) to have multiple cameras shake without adding them all as children of the shaker.

- Why use var and cast the result when the return types are known (float/double)?

- Have you checked if this works with cinemachine or if cinemachine has a builtin way to add screenshake?
